version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
    commit-message:
      prefix: "deps"
    rebase-strategy: "auto"
    target-branch: "develop"
    commit-signoff: true
    additional-properties:
      - file: "requirements.in"
